org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric 26.1.2
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.154.2+26.1.2
modmenu_version=18.0.0

# Mod
mod_version=1.3.0
maven_group=com.yagiz
archives_base_name=skinpowers
